name: CD

on:
  push:
    branches:
      - production

jobs:
  cd:
    runs-on: macos-latest # for the fonts in the OG image
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linter
        run: yarn run lint

      - name: Build
        run: yarn run build

      - name: Push to master branch
        run: |
          if [ -n "$(git diff --exit-code)" ]
          then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git fetch origin master
            git stash
            git checkout master
            git stash pop
            git add -A
            git commit -m "feat: update the OG images & og-imgs-cache.json"
            git push origin master
          fi

      - name: Checkout production branch
        run: git checkout production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: about.disfactory.tw
