name: CD

on:
  push:
    branches:
      - production
  schedule:
    # Translate the cron schedule into human-readable format: https://crontab.guru/
    # every day at midnight
    - cron: '0 0 * * *'

jobs:
  cd:
    runs-on: macos-latest # for the fonts in the OG image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: production

      - name: Setup node env
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 100000

      - name: Run linter
        run: yarn run lint

      - name: Build
        run: yarn run build

      - name: Push to dev branch
        run: |
          if [ -n "$(git diff --exit-code)" ]
          then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git fetch origin dev
            git stash
            git checkout dev
            git stash pop
            git add -A
            git commit -m "feat: update the OG images & og-imgs-cache.json"
            git push origin dev
          fi

      - name: Update production branch
        run: |
          git checkout production
          git pull -r origin production
          git rebase dev
          git push origin production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: about.disfactory.tw
